import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import ColorModeProvider from "@/provider/ThemeProvider";
import Navbar from "@/components/globals/navbar";

const averta = localFont({
  src: "../fonts/averta/averta.woff2",
  variable: "--font-averta",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={averta.className}>
        <ColorModeProvider>
          <Navbar />
          {children}
        </ColorModeProvider>
      </body>
    </html>
  );
}
