import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import ColorModeProvider from "@/provider/ThemeProvider";
import Navbar from "@/components/globals/navbar";

const averta = localFont({
  src: "../fonts/averta/id-averta-2.woff",
  variable: "--font-averta",
});

const avertaSemibold = localFont({
  src: "../fonts/averta/id-averta-1.woff",
  variable: "--font-averta-semibold",
});

const avertaBold = localFont({
  src: "../fonts/averta/id-averta-3.woff",
  variable: "--font-averta-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${averta.variable} ${avertaSemibold.variable} ${avertaBold.variable}`}
      >
        <ColorModeProvider>
          <Navbar />
          {children}
        </ColorModeProvider>
      </body>
    </html>
  );
}
